### ISSUE TITLE
working on multiple files

### ISSUE THREAD

**Issue by ghost** [cymonbr/SqlFormatter-VSCode#1]
when I am working on two SQL files and one is saved but another was is not saved yet, whenever I press alt+shift+f my second file text changes to first one

**Comment by cymonbr** [comment]
You can post the code for me look? I going verify his problem and answer you

**Comment by ghost** [comment]
hi
it doesnt depend on code
it works fine in a single file but with multiple file on different folders
or unsaved one it works wierd.

**Comment by cymonbr** [comment]
Ok, I going test here and find a solution. Thanks for show your issue.

**Comment by CosmKiwi** [comment]
Hi cymonbr,

The problem appears to be that it's getting the text to format from the first tab (as opposed to the currently selected tab), it then formats that text and inserts it over the top of the currently selected tab.

I assume the issue's at line 34 of SqlFormatter-VSCode/src/extension.ts and that:

`let text   = editor.document.getText();`

is returning the text of the first tab (instead of the selected tab).

**Comment by cymonbr** [comment]
Hi @AndyMc47, **thanks for your help**, the problem was the placement of the _variable_ that was _global_ and with that out of _scope_ of function and it should be called every _workspace_ change. Because of the work I was out of time to look at this, **thanks for the help again**.

**Correction performed successfully!**

**Comment by cymonbr** [comment]
Correction performed and published in **VSCode**, please if possible validate to verify that the correction has entered correctly. **Extension Version** _1.0.2_

**Comment by CosmKiwi** [comment]
That's working nicely now, thanks
